id: IB2334FCB
ocr_import_info:
  timestamp: '2023-09-26T07:44:33.629847+00:00'
  batch_id: batch-2436
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-26 09:15:31.967800+00:00
last_modified: 2023-09-26 09:15:31.967807+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W87
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW87
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ངག་དབང་བློ་བཟང་།
  languages:
  - bo
  author: ཀློང་རྡོལ་བླ་མ་ངག་དབང་བློ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.9416551316011917
  ocr_word_median_confidence_index: 0.99234194
bases:
  I4182:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4182
      total_pages: 1534
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4182.txt
    statistics:
      ocr_word_median_confidence_index: 0.99234194
      ocr_word_mean_confidence_index: 0.9416551316011917
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
